### ISSUE TITLE
Improve documentation of `phs_palettes` and `phs_palette_types`

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phsstyles#2]
I was on the documentation page for `scale_colour_discrete_phs` there's a nice description for `palette` and `type` so I know the default will be to use seq and 1 / main-purples. However, following the doc links the other help pages (for `phs_palettes` and `phs_palette_types`) don't really add anything.

Could those two doc pages be merged? And together explain all the values for type and palette? I'm thinking that a table would probably work well e.g. 

||seq| qual|
--- | --- | ---|
|1|main-purples|x|
|2|x|x|

**Comment by Tina815** [comment]
Hi James, thanks for the advice. I have added a simple table into `phs_palettes` and `phs_palette_types` help pages. Does it look fine? @Moohan
